/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UserImport } from './routes/user'
import { Route as RegistrationImport } from './routes/registration'
import { Route as LoginImport } from './routes/login'
import { Route as AdminImport } from './routes/admin'
import { Route as IndexImport } from './routes/index'
import { Route as TaskTasknameImport } from './routes/task.$taskname'
import { Route as CollectionCollectionIdImport } from './routes/collection.$collectionId'

// Create/Update Routes

const UserRoute = UserImport.update({
  path: '/user',
  getParentRoute: () => rootRoute,
} as any)

const RegistrationRoute = RegistrationImport.update({
  path: '/registration',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TaskTasknameRoute = TaskTasknameImport.update({
  path: '/task/$taskname',
  getParentRoute: () => rootRoute,
} as any)

const CollectionCollectionIdRoute = CollectionCollectionIdImport.update({
  path: '/collection/$collectionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/registration': {
      preLoaderRoute: typeof RegistrationImport
      parentRoute: typeof rootRoute
    }
    '/user': {
      preLoaderRoute: typeof UserImport
      parentRoute: typeof rootRoute
    }
    '/collection/$collectionId': {
      preLoaderRoute: typeof CollectionCollectionIdImport
      parentRoute: typeof rootRoute
    }
    '/task/$taskname': {
      preLoaderRoute: typeof TaskTasknameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRoute,
  LoginRoute,
  RegistrationRoute,
  UserRoute,
  CollectionCollectionIdRoute,
  TaskTasknameRoute,
])

/* prettier-ignore-end */
